services:
  - type: web
    name: nexabot-video-api
    runtime: python
    repo: https://github.com/sriragavanajanthan-cloud/NexaBotAI-Backend
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: CLEANUP_SECRET
        sync: false
